### ISSUE TITLE
ImportError for VASP jobs using pymatgen>=2019.9.12

### ISSUE THREAD

**Issue by astamminger** [materialsproject/custodian#108]
## System

* Custodian version: 2019.8.24
* Pymatgen version: 2019.9.16
* Python version: 3.7
* OS version: RHEL7

## Summary

* Custodian job for VASP fails with ``ImportError`` when trying to import ``VaspInput`` from pymatgen (2019.9.16)

## Error message

```
Traceback (most recent call last):
  File "/home/users/stamma58/.conda/envs/custodian/bin/cstdn", line 10, in <module>
    sys.exit(main())
  File "/home/users/stamma58/.conda/envs/custodian/lib/python3.7/site-packages/custodian/cli/cstdn.py", line 113, in main
    args.func(args)
  File "/home/users/stamma58/.conda/envs/custodian/lib/python3.7/site-packages/custodian/cli/cstdn.py", line 82, in run
    c = Custodian.from_spec(d)
  File "/home/users/stamma58/.conda/envs/custodian/lib/python3.7/site-packages/custodian/custodian.py", line 322, in from_spec
    cls_ = load_class(d["jb"])
  File "/home/users/stamma58/.conda/envs/custodian/lib/python3.7/site-packages/custodian/custodian.py", line 302, in load_class
    mod = __import__(modname, globals(), locals(), [classname], 0)
  File "/home/users/stamma58/.conda/envs/custodian/lib/python3.7/site-packages/custodian/vasp/jobs.py", line 13, in <module>
    from pymatgen.io.vasp import VaspInput, Incar, Poscar, Outcar, Kpoints, Vasprun
ImportError: cannot import name 'VaspInput' from 'pymatgen.io.vasp' (/home/users/stamma58/.conda/envs/custodian/lib/python3.7/site-packages/pymatgen/io/vasp/__init__.py)
```

## Suggested solution (if known)

Starting from pymatgen version 2019.9.12 `VaspInput` is no longer available from the `pymatgen.io.vasp` namespace. Suggested solution:

* Change imports of the from `from pymatgen.io.vasp import VaspInput` to `from pymatgen.io.vasp.inputs import VaspInput`

**Comment by astamminger** [comment]
Ahh I just realized that this is already fixed upstream! Sorry for the noise :)
