### ISSUE TITLE
v1.0.0 not compatible with pmg4.0

### ISSUE THREAD

**Issue by adengz** [materialsproject/custodian#29]
## System

* Custodian version: 1.0.0
* Python version: 3.5.1 & 2.7
* OS version: OS X 10.11.5 & Ubuntu (Circle CI)

## Summary

A few deprecated methods in pymatgen NOT removed in 1.0.0 release. 

## Example code

```python
>>> from custodian.vasp.jobs import VaspJob
```

## Error message

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zhideng/.pyenv/versions/3.5.1/Python.framework/Versions/3.5/lib/python3.5/site-packages/custodian/vasp/jobs.py", line 26, in <module>
    from pymatgen.io.smart import read_structure
ImportError: No module named 'pymatgen.io.smart'
```

## Suggested solution (if known)

Release a new stable version.

**Comment by shyuep** [comment]
Fixed in v1.0.1.
