### ISSUE TITLE
Check returncode to raise CustodianError() leading some trouble

### ISSUE THREAD

**Issue by specter119** [materialsproject/custodian#41]
When reporting bugs/issues, please supply the following information. If this 
is a feature request, please simply state the requested feature.

## System

* Custodian version: master
* Python version: 2.7
* OS version: CentOS release 6.8

## Summary

* the default terminate_on_nonzero_returncode is True.
* [_run_job](https://github.com/materialsproject/custodian/blob/master/custodian/custodian.py#L390L398) will raise a CustodianError() if returns a nonzero return code (in [L395](https://github.com/materialsproject/custodian/blob/master/custodian/custodian.py#L395)).
* something wrong gets in custodian.py  [L319~L323](https://github.com/materialsproject/custodian/blob/master/custodian/custodian.py#L319L323), it seems like missing total_errors, i am not sure.

## Example code

terminated sub slrum job with MPWorks

## Error message

```
$ more Eu1_S2_Sn1--GGA_opti-294848.error
INFO:custodian.custodian:Run started at 2016-12-19 21:03:28.011467 in /lustre/home/umjzhh-1/launcher/block_2016-10-12-18-29-00-023399/launcher_2016-12-19-13-03-16-629901.
INFO:custodian.custodian:Custodian running on Python version 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
INFO:custodian.custodian:Hostname: node077, Cluster: unknown
INFO:custodian.custodian:Starting job no. 1 (VaspJob) attempt no. 1. Errors thus far = 0.
INFO:root:Running srun -v -n 32 vasp
INFO:custodian.custodian:Terminating job
INFO:root:Terminate the job step using scancel --signal=KILL 294848.0
INFO:root:Backing up run to error.1.tar.gz.
ERROR:custodian.custodian:{u'handler': <custodian.vasp.handlers.VaspErrorHandler object at 0x2af91dd3d0d0>, u'errors': [u'brmix', u'eddrmm'], u'actions': [{u'action': {u'_set': {u'ISTART': 1}}, u'dict': u'INCAR'}, {u'action': {u'_set':
{u'POTIM': 0.25}}, u'dict': u'INCAR'}, {u'action': {u'_file_delete': {u'mode': u'actual'}}, u'file': u'CHGCAR'}, {u'action': {u'_file_delete': {u'mode': u'actual'}}, u'file': u'WAVECAR'}]}
INFO:custodian.custodian:Job return code is 137. Terminating...
ERROR:custodian.custodian:Job return code is 137. Terminating...
INFO:custodian.custodian:Logging to custodian.json...
INFO:custodian.custodian:Run ended at 2016-12-19 21:13:39.441558.
INFO:custodian.custodian:Run completed. Total time taken = 0:10:11.430091.
Traceback (most recent call last):
  File "/lustre/home/umjzhh-1/keliu/envs/mpworks/codes/fireworks/fireworks/core/rocket.py", line 224, in run
    m_action = t.run_task(my_spec)
  File "/lustre/home/umjzhh-1/keliu/envs/mpworks/codes/mpworks/mpworks/firetasks/custodian_task.py", line 136, in run_task
    custodian_out = c.run()
  File "/lustre/home/umjzhh-1/keliu/envs/mpworks/codes/custodian/custodian/custodian.py", line 323, in run
    .format(self.total_errors, ex))
RuntimeError: 1 errors reached: (CustodianError(...), u'Job return code is 137. Terminating...'). Exited...
INFO:rocket.launcher:Rocket finished
```

## Suggested solution (if known)

* I just comment L395, and everything turn back to be fine.

## Files

<If input files are needed for the error, please copy and paste them here.>

```
<contents of file 1>
```

**Comment by shyuep** [comment]
Casn't you call custodian simply with terminate_on_nonzero = False?

**Comment by shyuep** [comment]
Note that a nonzero return code usually means your job ended with errors. The safe course is always to terminate.

**Comment by specter119** [comment]
@shyuep Now I see it, I'll turn the terminate_on_nonzero off when necessary.
